import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FileDown, Loader2, Sparkles, LayoutTemplate } from 'lucide-react';
import AnoAI from '@/components/ui/animated-shader-background';
import { motion, AnimatePresence } from 'framer-motion';
import pptxgen from 'pptxgenjs';

export default function PptCreator() {
  const navigate = useNavigate();
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [mode, setMode] = useState<'ai' | 'template'>('ai');

  const handleGeneratePptAI = async () => {
    if (!topic.trim()) return;
    setLoading(true);
    setMessage("Generating content (this may take a moment)...");
    try {
      const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
      const res = await fetch(`${baseUrl}/api/generate_ppt`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic })
      });

      const contentType = res.headers.get("content-type");
      if (!contentType || !contentType.includes("application/json")) {
        throw new Error("Backend server is unreachable. Please ensure your Python backend is running!");
      }

      const data = await res.json();
      
      if (res.ok && data.slides) {
        setMessage("Building Presentation...");
        const pres = new pptxgen();
        
        // Title Slide
        const titleSlide = pres.addSlide();
        titleSlide.addText(topic.toUpperCase(), { x: 1, y: 2, w: 8, h: 1, fontSize: 36, bold: true, align: 'center' });
        titleSlide.addText("Generated by AI", { x: 1, y: 3, w: 8, h: 1, fontSize: 18, align: 'center', color: "888888" });

        // Content Slides
        data.slides.forEach((slideData: any) => {
          const slide = pres.addSlide();
          slide.addText(slideData.title, { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 28, bold: true });
          
          if (slideData.bullets && slideData.bullets.length > 0) {
              const formattedBullets = slideData.bullets.map((b: string) => ({ text: b, options: { bullet: true, breakLine: true } }));
              slide.addText(formattedBullets, { x: 0.5, y: 1.8, w: 9, h: 3.5, fontSize: 18, valign: 'top' });
          }
        });

        await pres.writeFile({ fileName: `${topic.replace(/\s+/g, '_')}.pptx` });
        setMessage("Presentation Downloaded successfully!");
      } else {
        setMessage("Error: " + (data.detail || "Failed to generate"));
      }
    } catch (err: any) {
      setMessage("Error Connecting: " + err.message);
    }
    setLoading(false);
  };

  const handleGenerateTemplate = async () => {
    setLoading(true);
    setMessage("Building Template...");
    try {
      const pres = new pptxgen();
      
      // Title Slide
      const titleSlide = pres.addSlide();
      const presentationTitle = topic.trim() ? topic.toUpperCase() : "My Presentation";
      titleSlide.addText(presentationTitle, { x: 1, y: 2, w: 8, h: 1, fontSize: 36, bold: true, align: 'center' });
      titleSlide.addText("Starter Template", { x: 1, y: 3, w: 8, h: 1, fontSize: 18, align: 'center', color: "888888" });

      // Content Slide 1
      const slide1 = pres.addSlide();
      slide1.addText("Introduction", { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 28, bold: true });
      slide1.addText([{ text: "Point 1", options: { bullet: true, breakLine: true } }, { text: "Point 2", options: { bullet: true, breakLine: true } }], { x: 0.5, y: 1.8, w: 9, h: 3.5, fontSize: 18, valign: 'top' });

      // Content Slide 2
      const slide2 = pres.addSlide();
      slide2.addText("Details", { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 28, bold: true });
      slide2.addText([{ text: "Add your details here...", options: { bullet: true, breakLine: true } }], { x: 0.5, y: 1.8, w: 9, h: 3.5, fontSize: 18, valign: 'top' });

      const fileName = topic.trim() ? `${topic.replace(/\s+/g, '_')}.pptx` : 'Presentation.pptx';
      await pres.writeFile({ fileName });
      setMessage("Template Downloaded successfully!");
    } catch (err: any) {
      setMessage("Error Generating PPT: " + err.message);
    }
    setLoading(false);
  };

  return (
    <div className="w-full min-h-screen text-foreground font-sans overflow-x-hidden relative flex flex-col">
      <div className="fixed inset-0 z-0">
        <AnoAI />
      </div>

      <div className="relative z-10 w-full max-w-7xl mx-auto p-4 md:p-8 flex flex-col flex-1">
        
        <header className="relative z-50 flex flex-col gap-6 mb-8 backdrop-blur-md bg-white/5 p-6 rounded-3xl border border-white/10 shadow-xl">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => navigate('/create')}
              className="p-2 rounded-full bg-white/10 hover:bg-white/20 transition-all active:scale-95"
            >
              <ArrowLeft className="w-6 h-6 text-white" />
            </button>
            <h1 className="text-2xl font-bold tracking-tight bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                PPT Creator
            </h1>
          </div>
        </header>

        <div className="flex-1 flex flex-col items-center justify-center min-h-[400px]">
            <AnimatePresence mode="wait">
                 <motion.div
                    key="content"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.2 }}
                    className="w-full max-w-2xl bg-white/5 border border-white/10 p-8 rounded-3xl backdrop-blur-md text-center shadow-2xl"
                >
                    <div className="flex bg-black/40 p-1 rounded-2xl mb-8">
                      <button 
                        onClick={() => { setMode('ai'); setMessage(''); }}
                        className={`flex-1 py-3 px-4 rounded-xl font-medium transition-all flex items-center justify-center gap-2 ${mode === 'ai' ? 'bg-white/10 text-white shadow-sm' : 'text-white/50 hover:text-white/80 hover:bg-white/5'}`}
                      >
                        <Sparkles className="w-4 h-4" /> AI Generate
                      </button>
                      <button 
                        onClick={() => { setMode('template'); setMessage(''); }}
                        className={`flex-1 py-3 px-4 rounded-xl font-medium transition-all flex items-center justify-center gap-2 ${mode === 'template' ? 'bg-white/10 text-white shadow-sm' : 'text-white/50 hover:text-white/80 hover:bg-white/5'}`}
                      >
                        <LayoutTemplate className="w-4 h-4" /> Starter Template
                      </button>
                    </div>

                    {mode === 'ai' ? (
                      <>
                        <h2 className="text-3xl font-bold mb-4">AI PPT Creator</h2>
                        <p className="text-white/60 mb-8">
                            Provide a topic and let AI structure the slides for you!
                        </p>
                        <div className="flex flex-col gap-4">
                            <input
                                type="text"
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                                placeholder="Enter a topic (e.g. The Future of AI)"
                                className="w-full bg-white/5 border border-white/10 rounded-xl p-4 text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                            />
                            
                            <button
                                onClick={handleGeneratePptAI}
                                disabled={loading || !topic.trim()}
                                className="bg-blue-500 hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed text-white py-4 px-6 rounded-xl transition-all flex items-center justify-center gap-2 font-semibold"
                            >
                                {loading ? <Loader2 className="w-5 h-5 animate-spin"/> : <Sparkles className="w-5 h-5"/>}
                                {loading ? "Processing..." : "Generate & Download PPT"}
                            </button>
                        </div>
                      </>
                    ) : (
                      <>
                        <h2 className="text-3xl font-bold mb-4">Starter Template</h2>
                        <p className="text-white/60 mb-8">
                            Generate a starter presentation locally. Provide an optional topic to customize the title!
                        </p>
                        <div className="flex flex-col gap-4">
                            <input
                                type="text"
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                                placeholder="Enter a topic (Optional, e.g. Quarterly Review)"
                                className="w-full bg-white/5 border border-white/10 rounded-xl p-4 text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                            />
                            
                            <button
                                onClick={handleGenerateTemplate}
                                disabled={loading}
                                className="bg-blue-500 hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed text-white py-4 px-6 rounded-xl transition-all flex items-center justify-center gap-2 font-semibold"
                            >
                                {loading ? <Loader2 className="w-5 h-5 animate-spin"/> : <FileDown className="w-5 h-5"/>}
                                {loading ? "Building..." : "Download Starter Template"}
                            </button>
                        </div>
                      </>
                    )}

                    {message && (
                        <p className="text-sm mt-4 text-white/80">{message}</p>
                    )}
                </motion.div>
            </AnimatePresence>
        </div>

      </div>
    </div>
  );
}
